
export enum Eventos {
    disconnect = "disconnect",
    connection = "connection",
    handshake_sucess = 'handshake-sucess',
    handshake = 'handshake',
    new_registration_requested = "new-registration-requested",
    new_message = "new-message",
    status_changed = "status-changed",
    user_online_request = "user-online-request",
    user_online_response = "user-online-response",
    message_received = "message-received",
    categoria_request = "categoria-request",
    categoria_response = "categoria-response",
    apontamento_request = "apontamento-request",
    apontamento_sucesso = "apontamento-sucesso",
    solicita_tarefa_atual_request = "solicita-tarefa-atual-request",
    solicita_tarefa_atual_response = "solicita-tarefa-atual-response",
    solicitacao_versao_atual_request = "solicitacao-versao-atual-request",
    solicitacao_versao_atual_response = "solicitacao-versao-atual-response",
}
